spring:
  application:
    name: notes
#mongodb
  data: 
    mongodb: 
#      host: localhost
#      port: 51544
#      database: notes
#      uri: mongodb://localhost/goLearn
      uri: mongodb://arshalJain:12345@ds123614.mlab.com:23614/notes
      #repositories:
        #enabled: true
        